# Generated by Django 5.2.6 on 2025-09-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('prefijo_codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='configuraciones_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_cambio_cop', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tasa_cambio_bs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mostrar_precios', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigoBarras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigoProducto', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.areaalmacen')),
                ('etiquetas', models.ManyToManyField(blank=True, to='system.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=100, unique=True)),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('fecha_llegada', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='system.producto')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('usos', models.TextField(blank=True)),
                ('contraindicaciones', models.TextField(blank=True)),
                ('advertencias_precauciones', models.TextField(blank=True)),
                ('reaccionesAdversas', models.TextField(blank=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.producto')),
            ],
        ),
    ]
