# Generated by Django 5.2.6 on 2025-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaalmacen',
            name='definicion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
