# Generated by Django 5.2.6 on 2025-09-24 16:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_areaalmacen_definicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\Respaldo\\Proyectos\\Proyecto-agropecuaria\\media'), upload_to='products_pictures/'),
        ),
    ]
