# Generated by Django 5.2.6 on 2025-09-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_producto_foto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='fecha_llegada',
            new_name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='codigo_lote',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='lote',
            name='costo_unitario_lote',
            field=models.DecimalField(decimal_places=4, default=100, help_text='Costo unitario real de esta compra.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(default=100, help_text='Número de lote del fabricante o interno.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio_referencia',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='Precio Venta Público'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, help_text='Nivel de stock para activar alerta de reorden.'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_actual',
            field=models.PositiveIntegerField(verbose_name='Stock del Lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.areaalmacen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='system.unidadmedida'),
        ),
    ]
