# Generated by Django 5.2.6 on 2025-09-15 17:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_usuario',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('usuario', 'Usuario'), ('invitado', 'Invitado')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Respaldo\\Proyectos\\Proyecto-agropecuaria\\media'), upload_to='pruebas/'),
        ),
    ]
