# Generated by Django 5.2.6 on 2025-09-16 18:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_nivel_usuario_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, choices=[('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Respaldo\\Proyectos\\Proyecto-agropecuaria\\media'), upload_to='profiles_pictures/'),
        ),
    ]
