# Generated by Django 5.2.6 on 2025-09-26 15:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_cargo_profile_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\Respaldo\\Proyectos\\Proyecto-agropecuaria\\media'), upload_to='profiles_pictures/'),
        ),
    ]
